/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_Cluster = map[string]string{
	"": "Cluster is the schema for the clusters API",
}

func (Cluster) SwaggerDoc() map[string]string {
	return map_Cluster
}

var map_ClusterSpec = map[string]string{
	"provider":    "Provider of the cluster: Openshift, Kubernetes, or other cloud providers",
	"category":    "cluster category, such as: Strict、NonStrict、Dev、Test、Pro",
	"description": "\n cluster description",
	"code":        "cluster code",
	"kubeconfig":  "kubernetes",
	"certData":    "Cert Data",
	"master":      "cluster master url",
}

func (ClusterSpec) SwaggerDoc() map[string]string {
	return map_ClusterSpec
}

var map_ClusterStatus = map[string]string{
	"version": "kubernetes version",
}

func (ClusterStatus) SwaggerDoc() map[string]string {
	return map_ClusterStatus
}

var map_Workspace = map[string]string{
	"": "Workspace is the Schema for the namespacegroups API",
}

func (Workspace) SwaggerDoc() map[string]string {
	return map_Workspace
}

var map_WorkspaceList = map[string]string{
	"": "WorkspaceList contains a list of Workspace",
}

func (WorkspaceList) SwaggerDoc() map[string]string {
	return map_WorkspaceList
}

var map_WorkspaceSpec = map[string]string{
	"code":              "workspace code",
	"description":       "workspace description",
	"namespaceSelector": "select which namespace will join to this group",
}

func (WorkspaceSpec) SwaggerDoc() map[string]string {
	return map_WorkspaceSpec
}

var map_WorkspaceStatus = map[string]string{
	"":                  "WorkspaceStatus defines the observed state of Workspace",
	"clusterNamespaces": "cluster's namespaces",
}

func (WorkspaceStatus) SwaggerDoc() map[string]string {
	return map_WorkspaceStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
